name: Question
description: Ask a question about Trae Agent
labels: ['type/question', 'status/need-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question form! Before asking a question, please make sure you have searched https://github.com/bytedance/trae-agent/issues to see if there are any existing issues that cover the same question.

  - type: textarea
    id: description
    attributes:
      label: What is your question?
      description: A clear and concise description of the question.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information that you believe is relevant to this question
      description: Add any other context about the question here.
    validations:
      required: false
